# Generated by Django 4.1.3 on 2022-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(max_length=200)),
                ('value', models.DateTimeField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('topic', models.CharField(max_length=200)),
                ('mail_from', models.CharField(max_length=500)),
                ('mail_to', models.CharField(max_length=500)),
                ('sent', models.DateTimeField(max_length=200)),
                ('read', models.DateTimeField(max_length=200, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('readcount', models.IntegerField(default=-1, null=True)),
            ],
        ),
    ]
