# Generated by Django 4.1.3 on 2022-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_pricefeature_alter_price_options_price_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricefeature',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='pricefeature',
            name='code',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
